# Generated by Django 5.1.3 on 2024-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cat",
            constraint=models.UniqueConstraint(
                fields=("name", "years", "breed", "salary"),
                name="unique_cat_combination",
            ),
        ),
    ]
