# Generated by Django 5.1.3 on 2024-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_cat_unique_cat_combination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
