# Generated by Django 5.1.3 on 2024-11-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_alter_target_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mission",
            old_name="is_completed",
            new_name="mission_completed",
        ),
        migrations.RenameField(
            model_name="target",
            old_name="is_complete",
            new_name="target_completed",
        ),
    ]
